import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import { SessionProvider } from "next-auth/react";
import Nav from "@/components/Navbar/Navbar";
const inter = Inter({ subsets: ["latin"] });
import { Toaster } from "@/components/ui/toaster"
import MainNav from "@/components/Navbar/MainNav";
import { CartContextProvider } from "@/hooks/useCart";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionProvider>
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap the children inside NextUIProvider */}
        <CartContextProvider >
              <Toaster />
   
              <Nav />
              {children}
            </CartContextProvider>
      </body>
    </html>
    </SessionProvider>
  );
}
